export const recurringStyles = {
  section: {
    container: "rounded-xl",
    emptyWrap: "p-6",
    emptyActionIcon: "h-4 w-4 mr-2",
    header: "p-3 border-b border-primary/20",
    headerRow: "flex items-center justify-between",
    headerLeft: "flex items-center gap-2",
    headerIconWrap: "flex size-8 items-center justify-center rounded-xl bg-primary/10",
    headerIcon: "w-4 h-4 text-primary",
    title: "text-base text-primary font-bold tracking-tight",
    subtitle: "text-xs text-primary/70",
    subtitleMuted: "text-primary/50",
    stats: "mt-3 pt-3 border-t border-primary/10 grid grid-cols-2 gap-2",
    statRow:
      "flex flex-col gap-1 rounded-xl border border-primary/10 bg-primary/5 px-3 py-2",
    statLeft: "flex items-center gap-2 min-w-0",
    statIconWrapPositive: "flex size-6 items-center justify-center rounded-lg bg-emerald-500/10",
    statIconPositive: "w-3 h-3 text-emerald-500",
    statIconWrapNegative: "flex size-6 items-center justify-center rounded-lg bg-red-500/10",
    statIconNegative: "w-3 h-3 text-red-500",
    statLabel: "text-xs text-primary/70",
    statValuePositive: "text-sm font-semibold text-emerald-500",
    statValueNegative: "text-sm font-semibold text-red-500",
    list: "p-2 space-y-2",
    footer: "px-4 pb-2 pt-1",
    footerText: "text-xs text-primary text-center",
  },
  form: {
    form: "space-y-4",
    errorWrap: "mb-4 p-3 rounded-lg bg-destructive/10 border border-destructive/20",
    errorText: "text-sm text-destructive",
    grid: "grid grid-cols-1 sm:grid-cols-2 gap-4",
  },
  formModal: {
    form: "space-y-2",
    content: "gap-2",
    error: "px-3 py-2 text-sm text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/20 rounded-md",
    section: "gap-2",
    grid: "grid grid-cols-1 sm:grid-cols-2 gap-3",
  },
} as const;
