export const onboardingStyles = {
  overlay: 'fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-sm px-3 sm:px-4 py-6 sm:py-8 overflow-y-auto',
  modal: 'w-full max-w-md sm:max-w-lg md:max-w-2xl rounded-2xl sm:rounded-3xl bg-card shadow-2xl p-4 sm:p-6 md:p-8 my-auto max-h-[90vh] flex flex-col',
  header: {
    container: 'mb-4 sm:mb-6 flex-shrink-0',
    content: 'flex items-start gap-3',
    icon: 'h-10 w-10 sm:h-12 sm:w-12 rounded-2xl bg-primary/10 flex items-center justify-center text-primary flex-shrink-0',
    meta: 'text-xs uppercase tracking-wide text-primary/70',
    title: 'text-xl sm:text-2xl font-semibold text-primary',
    description: 'text-xs sm:text-sm text-primary/70',
    progressTrack: 'mt-3 sm:mt-4 h-2 w-full rounded-full bg-primary/10',
    progressIndicator: 'h-full rounded-full bg-primary transition-all',
  },
  stepContent: 'space-y-4 overflow-y-auto pr-1 scrollbar-thin flex-1 min-h-0',
  card: 'rounded-xl border-2 border-primary/20 p-5 space-y-3 bg-card shadow-sm hover:shadow-md transition-shadow',
  cardHeader: 'flex items-center justify-between',
  cardTitle: 'text-sm font-semibold text-primary',
  deleteButton: 'text-primary/70 hover:text-destructive transition-colors disabled:opacity-50',
  addButton: 'w-full bg-primary text-primary-foreground hover:bg-card hover:text-primary border-2 border-primary transition-all font-medium flex items-center justify-center gap-2',
  backButton: 'bg-primary text-primary-foreground hover:bg-card hover:text-primary border-2 border-primary transition-all font-medium flex items-center gap-2',
  nextButton: 'bg-primary text-primary-foreground hover:bg-card hover:text-primary border-2 border-primary transition-all font-medium flex items-center justify-center gap-2',
  label: 'text-sm font-medium text-primary',
  primaryLabel: 'text-sm font-medium text-primary',
  input: 'h-11 bg-input border-2 border-primary/20 focus:border-primary text-primary placeholder:text-primary/40',
  select: 'h-11 bg-input border-2 border-primary/20 focus:border-primary',
  selectContent: 'bg-popover border-2 border-primary/20',
  alert: 'mt-4 sm:mt-5 rounded-2xl border border-destructive/30 bg-destructive/10 p-3 text-xs sm:text-sm text-destructive flex items-start gap-2 flex-shrink-0',
  footer: 'mt-4 sm:mt-6 flex flex-row items-center justify-between gap-3 flex-shrink-0',
  loadingInfo: 'flex items-center gap-2 text-sm text-primary/70',
  warningMessage: 'rounded-xl border border-warning/30 bg-warning/10 p-3 text-sm text-warning-foreground',
};

export type OnboardingStyles = typeof onboardingStyles;
