export const settingsStyles = {
  page: {
    container:
      "relative flex w-full min-h-[100svh] flex-col bg-card",
    style: { fontFamily: '"Inter", "SF Pro Display", system-ui, sans-serif' },
  },
  header: {
    container:
      "sticky top-0 z-20 bg-card/80 backdrop-blur-xl border-b border-primary/60 shadow-sm px-3 sm:px-4 py-2 sm:py-3",
    inner: "flex items-center justify-between",
    button:
      "text-primary hover:bg-primary hover:text-primary-foreground active:scale-95 rounded-2xl transition-all duration-200 ease-out p-2 sm:p-2.5 min-w-[44px] min-h-[44px] flex items-center justify-center shadow-sm hover:shadow-md",
    title: "text-lg sm:text-xl font-bold tracking-tight text-primary",
    spacer: "min-w-[44px] min-h-[44px]",
  },
  main: {
    container: "px-3 sm:px-4 py-3 pb-20 space-y-5",
  },
  profile: {
    header:
      "flex items-center justify-between gap-3",
    container: "flex items-center gap-3 flex-1 min-w-0",
    avatar:
      "size-16 rounded-2xl bg-primary flex items-center justify-center text-primary-foreground text-xl font-bold shadow-lg shadow-primary/30 shrink-0",
    info: "flex-1 min-w-0",
    name: "text-lg font-bold text-primary mb-1.5 truncate",
    badges: "flex items-center gap-1.5 flex-wrap",
    badge:
      "px-2 py-1 rounded-full text-[10px] font-semibold bg-primary/10 text-primary whitespace-nowrap border border-primary/20",
    editButton:
      "hover:bg-primary hover:text-primary-foreground active:scale-95 transition-all duration-200 border border-primary/20 bg-primary/10 text-primary rounded-xl px-3 py-1.5 text-sm font-semibold shadow-sm hover:shadow-md whitespace-nowrap shrink-0",
  },
  profileDetails: {
    container: "divide-y divide-primary/20",
  },
  skeletons: {
    shimmer: "animate-pulse bg-primary/12",
    headerIcon: "w-10 h-10 rounded-xl",
    headerTitle: "w-24 h-6 rounded-lg",
    section: "space-y-4",
    sectionTitle: "h-6 rounded-lg bg-primary/15 animate-pulse",
    card: "bg-card/95 backdrop-blur-sm shadow-xl shadow-[#7678e4]/15 border-0 rounded-2xl overflow-hidden",
    cardHeader: "flex items-center gap-4 px-2 py-4 bg-card",
    avatar: "size-16 rounded-2xl bg-primary/12 shrink-0 animate-pulse",
    headerBody: "flex-1 space-y-2",
    headerLinePrimary: "h-6 w-24 bg-primary/15 rounded-lg animate-pulse",
    headerLineSecondary: "h-4 w-32 bg-primary/15 rounded-lg animate-pulse",
    dividerLight: "divide-y divide-primary/40",
    dividerStrong: "divide-y divide-primary/60",
    listRow: "flex items-center gap-3 p-3",
    listRowSpace: "flex items-center justify-between p-3",
    listIcon: "size-10 bg-primary/12 rounded-xl shrink-0 animate-pulse",
    listBody: "flex-1 space-y-1",
    listLineShort: "h-3 w-16 bg-primary/15 rounded animate-pulse",
    listLineMedium: "h-3 w-24 bg-primary/15 rounded animate-pulse",
    listLineLong: "h-3 w-32 bg-primary/15 rounded animate-pulse",
    listLineXL: "h-4 w-32 bg-primary/15 rounded animate-pulse",
    listLineXLLong: "h-3 w-40 bg-primary/15 rounded animate-pulse",
    memberRow: "p-3 flex items-center justify-between",
    memberLeft: "flex items-center gap-3 flex-1",
    memberIcon: "w-10 h-10 bg-primary/12 rounded-xl shrink-0 animate-pulse",
    memberBody: "flex-1 space-y-1",
    switchPill: "w-16 h-8 bg-primary/12 rounded-full shrink-0 animate-pulse",
    cardHeaderCompact: "px-4 py-3 bg-card space-y-2",
    headerLineSmall: "h-4 w-32 bg-primary/15 rounded animate-pulse",
    headerLineTiny: "h-3 w-24 bg-primary/15 rounded animate-pulse",
    cardStack: "space-y-4",
    cardMargin: "mb-4",
  },
  modals: {
    actionsButton: "w-full sm:w-auto",
    loadingIcon: "mr-2 h-4 w-4 animate-spin",
    iconSmall: "mr-2 h-4 w-4",
    form: "space-y-4",
    field: {
      label: "block text-sm font-medium text-primary mb-1.5",
      input:
        "w-full px-3 py-2 text-sm rounded-lg border border-primary/20 bg-card text-primary placeholder:text-primary/60 focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary/20 disabled:opacity-50 disabled:cursor-not-allowed",
      inputError: "border-destructive focus:ring-destructive/20 focus:border-destructive",
      errorText: "mt-1.5 text-sm text-destructive",
    },
    title: "text-lg font-semibold text-primary",
    description: "text-sm text-primary/70",
    invite: {
      infoBox: "rounded-lg bg-primary/10 border border-primary/20 p-3",
      infoText: "text-sm text-primary",
      infoStrong: "font-semibold",
    },
    preference: {
      list: "space-y-2",
      itemBase:
        "w-full text-left px-4 py-3 rounded-lg border-2 transition-all flex items-start gap-3 hover:border-primary/40 hover:bg-primary/5 focus:outline-none focus:ring-2 focus:ring-primary/20 disabled:opacity-50 disabled:cursor-not-allowed",
      itemActive: "border-primary/20 bg-primary/10",
      itemIdle: "border-primary/20 bg-card",
      radioBase:
        "mt-0.5 shrink-0 w-5 h-5 rounded-full border-2 flex items-center justify-center transition-all",
      radioActive: "border-primary/20 bg-primary",
      radioIdle: "border-primary/20 bg-card",
      radioIcon: "h-3 w-3 text-primary-foreground",
      content: "flex-1 min-w-0",
      titleRow: "flex items-center gap-2",
      title: "text-sm font-semibold",
      titleActive: "text-primary",
      titleIdle: "text-primary",
      currentBadge: "text-xs px-2 py-0.5 rounded-full bg-primary/10 text-primary font-medium",
      description: "text-sm text-primary/70 mt-0.5",
    },
    subscription: {
      container: "space-y-4",
      cardBase: "rounded-lg border-2 p-4 transition-all",
      cardActive: "border-primary/20 bg-primary/5",
      cardIdle: "border-primary/20 bg-card",
      headerRow: "flex items-start justify-between mb-3",
      planTitle: "text-lg font-bold text-primary",
      planPrice: "text-2xl font-bold text-primary mt-1",
      planPriceSuffix: "text-sm font-normal text-primary/60",
      planBadge:
        "px-3 py-1 rounded-full bg-primary text-primary-foreground text-xs font-semibold",
      list: "space-y-2",
      listItem: "flex items-start gap-2",
      listIcon: "h-4 w-4 text-primary mt-0.5 shrink-0",
      listText: "text-sm text-primary/70",
      premiumBadgeWrap: "absolute top-0 right-0 w-24 h-24 -mr-12 -mt-12",
      premiumBadge:
        "absolute transform rotate-45 bg-linear-to-r from-primary to-primary/80 text-primary-foreground text-xs font-bold py-1 w-32 text-center shadow-md",
      premiumBadgeStyle: { top: "35px" },
      premiumTitleRow: "text-lg font-bold text-primary flex items-center gap-2",
      premiumIcon: "h-5 w-5 text-primary",
      secureRow: "mt-4 pt-4 border-t border-primary/20",
      secureText: "text-xs text-primary/60 text-center",
      secureIcon: "inline h-3 w-3 mr-1",
      cancelButton: "text-destructive hover:text-destructive hover:bg-destructive/10",
    },
    deleteAccount: {
      overlay:
        "fixed inset-0 z-9999 flex items-center justify-center bg-black/60 backdrop-blur-sm px-3 sm:px-4 py-6 sm:py-8",
      card: "w-full max-w-md rounded-2xl sm:rounded-3xl bg-card shadow-2xl p-6 sm:p-8 my-auto",
      header: "mb-6 flex items-start justify-between",
      headerLeft: "flex items-start gap-3 flex-1",
      headerContent: "flex-1",
      headerIconWrap:
        "h-12 w-12 rounded-2xl bg-destructive/10 flex items-center justify-center text-destructive shrink-0",
      headerIcon: "h-6 w-6",
      title: "text-xl sm:text-2xl font-semibold text-destructive",
      subtitle: "text-sm text-primary/70 mt-1",
      closeButton:
        "text-primary/80 hover:text-primary p-1 rounded-lg hover:bg-primary/10 transition-colors disabled:opacity-50",
      closeIcon: "h-5 w-5",
      body: "space-y-4 mb-6",
      bodyText: "text-sm text-primary",
      warningBox: "rounded-xl border-2 border-destructive/20 bg-destructive/5 p-4",
      warningTitle: "text-sm font-semibold text-destructive mb-2",
      warningList: "space-y-2 text-sm text-destructive/80",
      warningItem: "flex items-start gap-2",
      warningDot: "text-destructive mt-0.5",
      warningAlert:
        "rounded-lg bg-destructive/5 p-3 text-sm text-destructive border border-destructive/20 flex items-start gap-2",
      warningAlertIcon: "h-4 w-4 text-destructive mt-0.5",
      button: "w-full sm:w-auto",
      confirmButton: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
    },
  },
} as const;
