export const modalWrapperStyles = {
  dialogHeader: 'text-left',
  dialogTitle: 'text-lg font-semibold text-primary',
  dialogDescription: 'text-xs text-primary/70',
  dialogDescriptionHidden: 'sr-only',
  content: 'text-primary flex-1 overflow-y-auto pt-4',
  loadingWrap: 'flex items-center justify-center py-8',
  loadingDot: 'liquid-pulse size-8 rounded-full bg-primary/20',
  loadingText: 'ml-3 text-sm text-primary/70',
  drawerContent: 'p-0 pb-10',
  drawerHeader: 'text-left bg-card px-4 py-3 border-b border-primary/10 shrink-0 gap-0',
  drawerTitle: 'text-lg font-semibold text-primary',
  drawerDescription: 'text-xs text-primary/70',
  drawerContentBody: 'px-4 py-3 text-primary flex-1 overflow-y-auto',
  drawerFooter: 'pt-3 pb-4 px-4 border-t border-primary/10 bg-card shrink-0',
  modalSection: 'flex flex-col gap-4',
  modalSectionTitle: 'text-xs font-semibold text-primary/80 uppercase tracking-wide shrink-0 mb-2',
  modalActions: 'flex flex-col-reverse gap-2 sm:flex-row sm:justify-end py-4',
} as const;
